# Generated by Django 4.0.4 on 2022-11-29 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTramitante', models.CharField(max_length=80, unique=True)),
                ('correoTramitante', models.CharField(blank=True, max_length=64)),
                ('dependenciaTramitante', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVentanilla', models.CharField(max_length=20, unique=True)),
                ('tipoTramite', models.CharField(choices=[('P', 'PETICION'), ('Q', 'QUEJA'), ('R', 'RECLAMO'), ('S', 'SUGERENCIA'), ('F', 'FELICITACION')], default='P', max_length=1)),
                ('asunto', models.CharField(max_length=4000)),
                ('medioRecepcion', models.CharField(choices=[('WE', 'WEB'), ('ES', 'ESCRITO')], max_length=2)),
                ('fechaRecepcion', models.DateField()),
                ('fechaVencimiento', models.DateField(blank=True)),
                ('numeroOficio', models.CharField(blank=True, max_length=20)),
                ('oficioRespuesta', models.CharField(blank=True, max_length=500)),
                ('fechaRespuesta', models.DateField(blank=True)),
                ('nombrePeticionario', models.CharField(blank=True, max_length=80)),
                ('tipoPeticionario', models.CharField(blank=True, choices=[('PRE', 'ESTUDIANTE PREGRADO'), ('POS', 'ESTUDIANTE POSGRADO'), ('EMP', 'EMPLEADO'), ('DOC', 'DOCENTE'), ('EGR', 'EGRESADO'), ('JUB', 'JUBILADO'), ('EXT', 'PERSONA EXTERNA')], default='EXT', max_length=3)),
                ('direccionPeticionario', models.CharField(blank=True, max_length=50)),
                ('telefonoPeticionario', models.IntegerField(blank=True)),
                ('celularPeticionario', models.IntegerField(blank=True)),
                ('correoPeticionario', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTraslado', models.DateField()),
                ('idTramitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_tramite.tramitante')),
                ('idTramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_tramite.tramite')),
            ],
        ),
    ]
