# Generated by Django 4.0.4 on 2022-11-30 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tramitante', models.CharField(max_length=80, unique=True)),
                ('correo_tramitante', models.CharField(blank=True, max_length=64)),
                ('dependencia_tramitante', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ventanilla', models.CharField(max_length=20, unique=True)),
                ('tipo_tramite', models.CharField(choices=[('P', 'PETICION'), ('Q', 'QUEJA'), ('R', 'RECLAMO'), ('S', 'SUGERENCIA'), ('F', 'FELICITACION')], default='P', max_length=1)),
                ('asunto_tramite', models.CharField(max_length=4000)),
                ('medio_recepcion', models.CharField(choices=[('WE', 'WEB'), ('ES', 'ESCRITO')], default='WE', max_length=2)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_oficio', models.CharField(blank=True, max_length=20)),
                ('oficio_respuesta', models.CharField(blank=True, max_length=500)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('nombre_peticionario', models.CharField(blank=True, max_length=80)),
                ('tipo_peticionario', models.CharField(blank=True, choices=[('PRE', 'ESTUDIANTE PREGRADO'), ('POS', 'ESTUDIANTE POSGRADO'), ('EMP', 'EMPLEADO'), ('DOC', 'DOCENTE'), ('EGR', 'EGRESADO'), ('JUB', 'JUBILADO'), ('EXT', 'PERSONA EXTERNA')], default='EXT', max_length=3)),
                ('direccion_peticionario', models.CharField(blank=True, max_length=50)),
                ('telefono_peticionario', models.CharField(blank=True, max_length=12)),
                ('celular_peticionario', models.CharField(blank=True, max_length=12)),
                ('correo_peticionario', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traslado', models.DateField()),
                ('id_tramitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_tramite.tramitante')),
                ('id_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_tramite.tramite')),
            ],
        ),
    ]
