# Generated by Django 4.0.4 on 2022-11-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tramite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='celularPeticionario',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='telefonoPeticionario',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
