# Generated by Django 4.0.4 on 2022-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_tramite', '0003_alter_tramite_mediorecepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='fechaRespuesta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
