# Generated by Django 4.1.3 on 2022-12-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_configuracion', models.CharField(max_length=20, unique=True)),
                ('tiempo_limite', models.IntegerField()),
            ],
        ),
    ]
