# Generated by Django 4.1.3 on 2022-12-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='nombre_configuracion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tipo_configuracion',
            field=models.CharField(choices=[('P', 'PETICION'), ('Q', 'QUEJA'), ('R', 'RECLAMO'), ('S', 'SUGERENCIA')], max_length=1, unique=True),
        ),
    ]
