# Generated by Django 4.1.3 on 2022-12-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_configuracion', '0002_configuracion_nombre_configuracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='nombre_configuracion',
        ),
    ]
